apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: coniiti
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - stateful-services.yaml
  - apps.yaml
  - ingress.yaml
