apiVersion: v1
kind: Secret
metadata:
  name: coniiti-secrets
  namespace: coniiti
type: Opaque
stringData:
  JWT_SECRET_KEY: "replace-with-strong-secret"
  RABBITMQ_DEFAULT_USER: "coniiti_mq"
  RABBITMQ_DEFAULT_PASS: "changeme"
